config/routes.rb
Rails.application.routes.draw do
  root 'user#new'
  resources 'user'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
    @user = User.create( user_params )
  end
  def index
    User.all
  end
  private
  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/index.html.erb
<%= image_tag @user.image.url(:small) %>

app/views/user/new.html.erb
<%= form_for @user, :url => user_index_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>